"""init

Revision ID: 795ca4608cd2
Revises: 
Create Date: 2025-11-04 03:55:55.972187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '795ca4608cd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('actor_region_code', sa.String(length=10), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique identifier for the region'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Name of the region'),
    sa.Column('code', sa.String(length=10), nullable=False, comment="Unique code for the region (e.g., 'JKT' for Jakarta)"),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment="IANA timezone name (e.g., 'Asia/Jakarta')"),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Whether the region is active'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the region was created'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the region was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('search_query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='regional_admin', nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Jakarta', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama Taman'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL-friendly name'),
    sa.Column('sk_penetapan', sa.String(length=255), nullable=True, comment='Nomor SK Penetapan'),
    sa.Column('pengelola', sa.String(length=255), nullable=True, comment='Instansi Pengelola'),
    sa.Column('provinsi', sa.String(length=100), nullable=True, comment='Provinsi'),
    sa.Column('kota_kabupaten', sa.String(length=100), nullable=True, comment='Kota/Kabupaten'),
    sa.Column('kecamatan', sa.String(length=100), nullable=True, comment='Kecamatan'),
    sa.Column('desa_kelurahan', sa.String(length=100), nullable=True, comment='Desa/Kelurahan'),
    sa.Column('tipe_ekoregion', sa.String(length=100), nullable=True, comment='Tipe Ekoregion'),
    sa.Column('area_ha', sa.Numeric(precision=10, scale=2), nullable=True, comment='Luas dalam hektar'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Latitude koordinat taman'),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Longitude koordinat taman'),
    sa.Column('description', sa.Text(), nullable=True, comment='Deskripsi Umum'),
    sa.Column('kondisi_fisik', sa.Text(), nullable=True, comment='Kondisi Fisik Kawasan'),
    sa.Column('nilai_penting', sa.Text(), nullable=True, comment='Nilai Penting Kawasan'),
    sa.Column('sejarah', sa.Text(), nullable=True, comment='Sejarah Taman'),
    sa.Column('visi', sa.Text(), nullable=True, comment='Visi Taman'),
    sa.Column('misi', sa.Text(), nullable=True, comment='Misi Taman'),
    sa.Column('nilai_dasar', sa.Text(), nullable=True, comment='Nilai-nilai Dasar'),
    sa.Column('gambar_utama', sa.String(length=500), nullable=True, comment='URL gambar utama taman'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True, comment='User who created/submitted this park'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Rejection reason or backup data for approved park edits'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # Add FK constraint from users to parks AFTER parks table is created
    op.create_foreign_key('fk_users_park_id', 'users', 'parks', ['park_id'], ['id'], source_schema=None, referent_schema=None)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True, comment='User who created/submitted this activity'),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fauna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('local_name', sa.String(), nullable=True),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('genus', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('ordo', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('habitat', sa.Text(), nullable=True),
    sa.Column('diet', sa.Text(), nullable=True),
    sa.Column('behavior', sa.Text(), nullable=True),
    sa.Column('morphology', sa.Text(), nullable=True),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('habitat_sumber_makanan', sa.Text(), nullable=True),
    sa.Column('status_hama', sa.String(length=50), nullable=True),
    sa.Column('tingkat_hama', sa.String(length=50), nullable=True),
    sa.Column('gambar_utama', sa.String(length=500), nullable=True),
    sa.Column('is_endemic', sa.Boolean(), nullable=False),
    sa.Column('iucn_status', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('local_name', sa.String(), nullable=True),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('genus', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('synonym', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('habitat', sa.Text(), nullable=True),
    sa.Column('morphology', sa.Text(), nullable=True),
    sa.Column('flowering_time', sa.String(length=100), nullable=True),
    sa.Column('distribution', sa.Text(), nullable=True),
    sa.Column('propagation_method', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('uses', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('gambar_utama', sa.String(length=500), nullable=True),
    sa.Column('leaf_image_url', sa.String(length=500), nullable=True),
    sa.Column('stem_image_url', sa.String(length=500), nullable=True),
    sa.Column('flower_image_url', sa.String(length=500), nullable=True),
    sa.Column('fruit_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_endemic', sa.Boolean(), nullable=False),
    sa.Column('iucn_status', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('target_audience', sa.String(length=50), nullable=False, comment='Target audience: super_admin, regional_admin'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='Priority level (0=normal, 1=high, 2=urgent)'),
    sa.Column('is_featured', sa.Boolean(), nullable=True, comment='Whether this announcement is featured'),
    sa.Column('is_pinned', sa.Boolean(), nullable=True, comment='Whether this announcement is pinned to top'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='When the announcement was published'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When the announcement expires'),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True, comment='URL to featured image'),
    sa.Column('attachments', sa.Text(), nullable=True, comment='JSON string of attachment URLs'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='Comma-separated tags'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='Number of views'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True, comment='Priority level (0=normal, 1=high, 2=urgent)'),
    sa.Column('is_featured', sa.Boolean(), nullable=True, comment='Whether this news is featured'),
    sa.Column('is_pinned', sa.Boolean(), nullable=True, comment='Whether this news is pinned to top'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='When the news was published'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When the news expires'),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True, comment='URL to featured image'),
    sa.Column('attachments', sa.Text(), nullable=True, comment='JSON string of attachment URLs'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='Comma-separated tags'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='Number of views'),
    sa.Column('reading_time', sa.Integer(), nullable=True, comment='Estimated reading time in minutes'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['announcement_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_region_code'), 'audit_logs', ['actor_region_code'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_notifications_from_user_id'), 'notifications', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_region_code'), 'notifications', ['region_code'], unique=False)
    op.create_index(op.f('ix_notifications_to_user_id'), 'notifications', ['to_user_id'], unique=False)
    op.create_index(op.f('ix_parks_id'), 'parks', ['id'], unique=False)
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_search_query_logs_normalized_query'), 'search_query_logs', ['normalized_query'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_park_id'), 'users', ['park_id'], unique=False)
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_index(op.f('ix_announcements_status'), 'announcements', ['status'], unique=False)
    op.create_index(op.f('ix_announcements_title'), 'announcements', ['title'], unique=False)
    op.create_index(op.f('ix_announcements_type'), 'announcements', ['type'], unique=False)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_galleries_author_id'), 'galleries', ['author_id'], unique=False)
    op.create_index(op.f('ix_galleries_entity_id'), 'galleries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_galleries_entity_type'), 'galleries', ['entity_type'], unique=False)
    op.create_index(op.f('ix_galleries_id'), 'galleries', ['id'], unique=False)
    op.create_index(op.f('ix_news_category'), 'news', ['category'], unique=False)
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_index(op.f('ix_news_slug'), 'news', ['slug'], unique=True)
    op.create_index(op.f('ix_news_status'), 'news', ['status'], unique=False)
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=False)
    op.create_index(op.f('ix_announcement_comments_id'), 'announcement_comments', ['id'], unique=False)
    op.create_index('idx_announcement_user_reaction', 'announcement_reactions', ['announcement_id', 'user_id', 'reaction_type'], unique=True)
    op.create_index(op.f('ix_announcement_reactions_id'), 'announcement_reactions', ['id'], unique=False)
    op.create_index('idx_announcement_user_read', 'announcement_reads', ['announcement_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_announcement_reads_id'), 'announcement_reads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcement_reads_id'), table_name='announcement_reads')
    op.drop_index('idx_announcement_user_read', table_name='announcement_reads')
    op.drop_table('announcement_reads')
    op.drop_index(op.f('ix_announcement_reactions_id'), table_name='announcement_reactions')
    op.drop_index('idx_announcement_user_reaction', table_name='announcement_reactions')
    op.drop_table('announcement_reactions')
    op.drop_index(op.f('ix_announcement_comments_id'), table_name='announcement_comments')
    op.drop_table('announcement_comments')
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_index(op.f('ix_news_status'), table_name='news')
    op.drop_index(op.f('ix_news_slug'), table_name='news')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_index(op.f('ix_news_category'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_galleries_id'), table_name='galleries')
    op.drop_index(op.f('ix_galleries_entity_type'), table_name='galleries')
    op.drop_index(op.f('ix_galleries_entity_id'), table_name='galleries')
    op.drop_index(op.f('ix_galleries_author_id'), table_name='galleries')
    op.drop_table('galleries')
    op.drop_table('flora')
    op.drop_table('fauna')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_announcements_type'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_title'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_status'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_park_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_search_query_logs_normalized_query'), table_name='search_query_logs')
    op.drop_table('search_query_logs')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_parks_id'), table_name='parks')
    op.drop_table('parks')
    op.drop_index(op.f('ix_notifications_to_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_region_code'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_from_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_region_code'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
