#!/bin/bash

# Setup local environment to match server configuration
# This script creates .env file with Supabase database connection

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 SETUP LOCAL ENVIRONMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Navigate to backend directory
cd apps/backend

# Check if .env already exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists in apps/backend/"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Aborted. Keeping existing .env file."
        exit 1
    fi
    echo "📝 Backing up existing .env to .env.backup"
    cp .env .env.backup
fi

# Get Supabase password
echo "🔐 Enter your Supabase database password:"
read -s SUPABASE_PASSWORD
echo ""

if [ -z "$SUPABASE_PASSWORD" ]; then
    echo "❌ Password cannot be empty!"
    exit 1
fi

# Escape special characters in password for URL
ESCAPED_PASSWORD=$(printf '%s' "$SUPABASE_PASSWORD" | sed 's/[[\.*^$()+?{|]/\\&/g')

# Create .env file in apps/backend/
cat > .env << EOF
# 🌍 Taman Kehati Environment Configuration
# Generated by setup-local-env.sh
# ⚠️  IMPORTANT: Never commit this file to version control

# =============================================================================
# DATABASE CONFIGURATION - SUPABASE
# =============================================================================

# PostgreSQL Database URLs for Supabase
DATABASE_URL="postgresql+asyncpg://postgres.kztboidieltsdlbzoadk:${ESCAPED_PASSWORD}@aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres"
DATABASE_URL_SYNC="postgresql://postgres.kztboidieltsdlbzoadk:${ESCAPED_PASSWORD}@aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres"

# Redis Cache URL (optional for local development)
REDIS_URL="redis://localhost:6379"

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================

# JWT Secret Key - Generate with: python3 -c "import secrets; print(secrets.token_urlsafe(32))"
SECRET_KEY="your-secret-key-change-in-production-make-it-long-and-secure"

# JWT Algorithm
ALGORITHM="HS256"

# Token expiration time in minutes
ACCESS_TOKEN_EXPIRE_MINUTES="30"

# =============================================================================
# FIREWALL CONFIGURATION
# =============================================================================

FIREWALL_ENABLED="false"
FIREWALL_MODE="blacklist"
IP_WHITELIST=""
IP_BLACKLIST=""
FIREWALL_BYPASS_PATHS="/health,/healthz,/api/health"

# =============================================================================
# CORS CONFIGURATION
# =============================================================================

CORS_ORIGINS="http://localhost:3000,http://frontend:3000"

# =============================================================================
# ENVIRONMENT SETTINGS
# =============================================================================

ENVIRONMENT="development"
DEBUG="true"

# =============================================================================
# FRONTEND CONFIGURATION
# =============================================================================

NEXT_PUBLIC_API_URL="http://localhost:8000"
API_BASE_URL="http://backend:8000"

# =============================================================================
# DATABASE POOL SETTINGS
# =============================================================================

DB_POOL_SIZE="10"
DB_MAX_OVERFLOW="20"
DB_POOL_TIMEOUT="30"
DB_POOL_RECYCLE="3600"

# =============================================================================
# FILE UPLOAD SETTINGS
# =============================================================================

MAX_FILE_SIZE="10485760"
ALLOWED_FILE_TYPES="image/jpeg,image/png,image/webp"
UPLOAD_DIRECTORY="./uploads"

# =============================================================================
# AI SERVICE CONFIGURATION
# =============================================================================

AI_PROVIDER="ollama"
OLLAMA_BASE_URL="http://localhost:11434"
OLLAMA_MODEL="qwen2:1.5b"

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================

LOG_LEVEL="INFO"
LOG_FORMAT="json"
LOG_FILE="logs/app.log"

# =============================================================================
# NEXT.JS CONFIGURATION
# =============================================================================

NODE_ENV="development"
NEXT_TELEMETRY_DISABLED="1"
NEXT_PUBLIC_APP_NAME="Taman Kehati"
NEXT_PUBLIC_APP_VERSION="2.1.0"

# =============================================================================
# MAP CONFIGURATION
# =============================================================================

NEXT_PUBLIC_MAP_TILE_URL="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
NEXT_PUBLIC_MAP_ATTRIBUTION="© OpenStreetMap contributors"
NEXT_PUBLIC_DEFAULT_LAT="-6.2088"
NEXT_PUBLIC_DEFAULT_LNG="106.8456"
NEXT_PUBLIC_DEFAULT_ZOOM="10"

# =============================================================================
# FEATURE FLAGS
# =============================================================================

NEXT_PUBLIC_ENABLE_AI="true"
NEXT_PUBLIC_ENABLE_MAPS="true"
NEXT_PUBLIC_ENABLE_UPLOADS="true"
NEXT_PUBLIC_ENABLE_NOTIFICATIONS="true"
EOF

echo "✅ .env file created successfully in apps/backend/.env"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Next steps:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Verify .env file:"
echo "   cat apps/backend/.env | grep DATABASE_URL"
echo ""
echo "2. Run Alembic migrations:"
echo "   cd apps/backend"
echo "   alembic upgrade head"
echo ""
echo "3. Test database connection:"
echo "   python -c \"from core.database.session import get_db; next(get_db())\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

