#!/bin/bash

# Setup frontend environment variables for local development
# This script creates .env.local file in apps/frontend/

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 SETUP FRONTEND ENVIRONMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "ℹ️  Note: Menggunakan .env.local (tidak di-commit ke Git)"
echo "   Untuk production, environment variables di-set via hosting platform"
echo ""

# Navigate to frontend directory
cd apps/frontend

# Check if .env.local already exists
if [ -f .env.local ]; then
    echo "⚠️  .env.local file already exists in apps/frontend/"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Aborted. Keeping existing .env.local file."
        exit 1
    fi
    echo "📝 Backing up existing .env.local to .env.local.backup"
    cp .env.local .env.local.backup
fi

# Also check if user wants to use .env instead
echo ""
read -p "Use .env instead of .env.local? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    ENV_FILE=".env"
    echo "⚠️  Using .env (will be committed to Git if not in .gitignore)"
else
    ENV_FILE=".env.local"
    echo "✅ Using .env.local (safe, won't be committed)"
fi

if [ -f "$ENV_FILE" ] && [ "$ENV_FILE" = ".env" ]; then
    echo "⚠️  .env file already exists"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Aborted. Keeping existing .env file."
        exit 1
    fi
    echo "📝 Backing up existing .env to .env.backup"
    cp .env .env.backup
fi

# Get API URL
echo "🌐 Enter backend API URL:"
echo "   (Default: http://localhost:8000 for local development)"
read -p "API URL [http://localhost:8000]: " API_URL
API_URL=${API_URL:-http://localhost:8000}

# Remove trailing slash if present
API_URL=${API_URL%/}

# Create environment file
cat > "$ENV_FILE" << EOF
# 🌍 Taman Kehati Frontend Environment Configuration
# Generated by setup-frontend-env.sh
# ⚠️  IMPORTANT: Never commit this file to version control

# =============================================================================
# API CONFIGURATION
# =============================================================================

# Backend API URL
# For local development: http://localhost:8000
# For production: https://your-production-api.com
NEXT_PUBLIC_API_URL="${API_URL}"

# =============================================================================
# APP CONFIGURATION
# =============================================================================

NEXT_PUBLIC_APP_NAME="Taman Kehati"
NEXT_PUBLIC_APP_VERSION="2.1.0"

# =============================================================================
# NEXT.JS CONFIGURATION
# =============================================================================

NODE_ENV="development"
NEXT_TELEMETRY_DISABLED="1"

# =============================================================================
# FEATURE FLAGS
# =============================================================================

NEXT_PUBLIC_ENABLE_AI="true"
NEXT_PUBLIC_ENABLE_MAPS="true"
NEXT_PUBLIC_ENABLE_UPLOADS="true"
NEXT_PUBLIC_ENABLE_NOTIFICATIONS="true"

# =============================================================================
# MAP CONFIGURATION
# =============================================================================

NEXT_PUBLIC_MAP_TILE_URL="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
NEXT_PUBLIC_MAP_ATTRIBUTION="© OpenStreetMap contributors"
NEXT_PUBLIC_DEFAULT_LAT="-6.2088"
NEXT_PUBLIC_DEFAULT_LNG="106.8456"
NEXT_PUBLIC_DEFAULT_ZOOM="10"
EOF

echo "✅ $ENV_FILE file created successfully in apps/frontend/$ENV_FILE"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Configuration:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   API URL: ${API_URL}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Next steps:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Install dependencies (if not already):"
echo "   cd apps/frontend"
echo "   npm install"
echo ""
echo "2. Start development server:"
echo "   npm run dev"
echo ""
echo "3. Frontend will be available at:"
echo "   http://localhost:3000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

